repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: scalpel
  description: Isoform quantification using 3'tagged scRNA-seq data
  author: Franz AKE
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - gpu
  is_nfcore: true
